version: '3.8'

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args:
        - DOMAIN=${DOMAIN:-rhanitra.42.fr}
    extra_hosts:
      - "rhanitra.42.fr:127.0.0.1"
    image: nginx:v1.0.0
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - DOMAIN=${DOMAIN:-rhanitra.42.fr}
      - TLS_VERSION=${TLS_VERSION:-TLSv1.3}
    restart: unless-stopped
    depends_on:
      - wordpress
    networks:
      - inception-network

  mariadb:
    image: mariadb:10.6
    container_name: mariadbr
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-wordpress}
      MYSQL_USER: ${MYSQL_USER:-wordpress}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-wordpress}
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - inception-network

  wordpress:
    image: wordpress:6.2
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE:-wordpress}
      WORDPRESS_DB_USER: ${MYSQL_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD:-wordpress}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-false}
    volumes:
      - wordpress_data:/var/www/html
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - inception-network

volumes:
  mariadb_data:
  wordpress_data:

networks:
  inception-network:
    driver: bridge