version: '3.8'

services:
  nginx:
    build:
      context: ./srcs/requirements/nginx
      dockerfile: Dockerfile
      args:
        - DOMAIN=${DOMAIN}
    image: nginx:v1.0.0
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./srcs/requirements/nginx/dist:/usr/share/nginx/html
      - ./srcs/requirements/nginx/conf:/etc/nginx/conf.d
    environment:
      - DOMAIN=${DOMAIN}
      - TLS_VERSION=${TLS_VERSION}
    restart: unless-stopped
    networks:
      - inception-network

networks:
  inception-network:
    driver: bridge