version: '3.8'

services:
  nginx:
    build:
      context: ./srcs/requirements/nginx
      dockerfile: Dockerfile
    image: mynginx:v1.0.0
    container_name: mynginx
    ports:
      - "${NGINX_PORT}:8080"
    volumes:
      - ./srcs/requirements/nginx/dist:/usr/share/nginx/html
      - ./srcs/requirements/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_PORT=${NGINX_PORT}
      - NGINX_DOC_ROOT=/usr/share/nginx/html
    restart: unless-stopped
    networks:
      - inception-network

networks:
  inception-network:
    driver: bridge