version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:inception
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-p$(cat /run/secrets/MYSQL_ROOT_PASSWORD)"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ${DATA_PATH}/db_data:/var/lib/mysql
    secrets:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
    networks:
      - inception-network

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:inception
    container_name: wordpress
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/ || exit 0"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
    volumes:
      - ${DATA_PATH}/wp_data:/var/www/html
    secrets:
      - WORDPRESS_DB_PASSWORD
      - WORDPRESS_USER_PASSWORD
      - WORDPRESS_ADMIN_PASSWORD
    networks:
      - inception-network

  nginx:
    build: ./requirements/nginx
    image: nginx:inception
    container_name: nginx
    restart: always
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`rhanitra.42.fr`)"
    volumes:
      - ${DATA_PATH}/wp_data:/var/www/html
      - ./requirements/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ../secrets/certs:/etc/ssl/private/
    networks:
      - inception-network

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/db_data
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/wp_data

networks:
  inception-network:
    driver: bridge

secrets:
  MYSQL_ROOT_PASSWORD:
    file: ../secrets/MYSQL_ROOT_PASSWORD.txt
  MYSQL_PASSWORD:
    file: ../secrets/MYSQL_PASSWORD.txt
  WORDPRESS_DB_PASSWORD:
    file: ../secrets/WORDPRESS_DB_PASSWORD.txt
  WORDPRESS_ADMIN_PASSWORD:
    file: ../secrets/WORDPRESS_ADMIN_PASSWORD.txt
  WORDPRESS_USER_PASSWORD:
    file: ../secrets/WORDPRESS_USER_PASSWORD.txt