services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:inception
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      MYSQL_DATABASE: db_name
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_pass
    volumes:
      - /home/rhanitra/data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    networks:
      - inception-network

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:inception
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      WORDPRESS_DB_NAME: db_name
      WORDPRESS_DB_USER: user_name
      WORDPRESS_DB_PASSWORD: user_pass
      WORDPRESS_TABLE_PREFIX: wp_
    volumes:
      - /home/rhanitra/data/html:/var/www/html
    ports:
      - "9000:9000"
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception-network

  nginx:
    build: ./requirements/nginx
    image: nginx:inception
    container_name: nginx
    ports:
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf.d
      - /home/rhanitra/data/html:/var/www/html
    restart: always
    depends_on:
      - wordpress
    networks:
      - inception-network

networks:
  inception-network:
    driver: bridge
