version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:inception
    container_name: mariadb
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception-network

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:inception
    container_name: wordpress
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception-network

  nginx:
    build: ./requirements/nginx
    image: nginx:inception
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`rhanitra.42.fr`)"
    volumes:
      - wp_data:/var/www/html
      - ./requirements/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ../secrets/certs:/etc/ssl/private/
    networks:
      - inception-network

volumes:
  db_data:
    driver: local
  wp_data:
    driver: local

networks:
  inception-network:
    driver: bridge

# secrets:
#   dbpass:
#     file: ../secrets/mdpMysql.txt
#   dbrootpass:
#     file: ../secrets/mdpdbroot.txt
#   wppassadmin:
#     file: ../secrets/mdpwpadmin.txt
#   wppassuser:
#     file: ../secrets/mdpwpuser.txt