-- Crée la base de données
CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE};

-- Crée l'utilisateur et lui donne les droits
CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'%';
FLUSH PRIVILEGES;
